# Generated by Django 2.2.12 on 2020-07-04 05:13

import django.db.models.deletion
from django.db import migrations, models

import django_tagulous.models.fields
import django_tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tagulous_CapitalisedTest_tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(django_tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="Tagulous_CapitalisedTest_singletag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(django_tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name="CapitalisedTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "singletag",
                    django_tagulous.models.fields.SingleTagField(
                        _set_tag_meta=True,
                        blank=True,
                        force_lowercase=True,
                        initial="coding, eating, gaming",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tagulousTestsApp3.Tagulous_CapitalisedTest_singletag",
                    ),
                ),
                (
                    "tags",
                    django_tagulous.models.fields.TagField(
                        _set_tag_meta=True,
                        blank=True,
                        force_lowercase=True,
                        help_text="Enter a comma-separated tag string",
                        initial="coding, eating, gaming",
                        to="tagulousTestsApp3.Tagulous_CapitalisedTest_tags",
                    ),
                ),
            ],
        ),
    ]
